--- # my conditional playbooks 
- name: 
  hosts: all
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: install httpd in RedHat family OS
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"


    - name: starting httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"


    - name: install apache2 in Debain family OS
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: starting apache2 service
      service: 
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy index file from server to host
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: ritika
        mode: 0777
