--- 
- name: my playbook to install and start service in different format
  hosts: all
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present

    - name: starting httpd service
      service:
        name: httpd
        state: started
