--- # my playbook to install multiple software
- name:
  hosts: webserver[0:2]
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: installing multiple packages
      yum:
        name: ['httpd','java','git','tree','mysql','docker']
        state: absent

