--- #
- name: 
  hosts: all
  become: yes
  user: ansible
  connection: ssh

  vars_files:
    - user.yml

  tasks:
    - name: creating user {{user1}}
      user:
        name: "{{user1}}"
        state: present
