---
# tasks file for setup-apache-role
- name: install httpd
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: install apache2
  apt: 
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copy index.html file from server to host
  copy:
    src: /home/ansible/index.html
    dest: /var/www/html
    mode: 0777
